print("Привет меня зовут Жарвис, а тебя как зовут?")
name = input()
print("Как дела " + name +" ?")
print("Загадай целое число:")
number_1 = input()
print("Загадай второе число:")
number_2 = input()
sum=int(number_1)+int(number_2)
print("Сумма этих чисел: " + str(sum))